name: Build Windows

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to upload to'
        default: ''

jobs:
  build-windows:
    runs-on: windows-2019

    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Download VapourSynth headers
      shell: bash
      run: |
        curl -s -o vs.zip -L https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth-*/ vapoursynth/
        mkdir -p "C:/Program Files/VapourSynth/sdk/include/"
        mv vapoursynth/include "C:/Program Files/VapourSynth/sdk/include/vapoursynth"

    - name: Download Qt
      shell: cmd
      run: |
        curl -Lo d:\qt.7z https://github.com/AmusementClub/VapourSynth-Editor/releases/download/qt-6.2.3/qt-install.7z
        curl -Lo d:\jom.zip https://qt.mirror.constant.com/official_releases/jom/jom_1_1_3.zip
        mkdir d:\qt-install
        cd d:\qt-install
        7z x ../qt.7z
        unzip -d bin d:\jom.zip

    - name: Build
      shell: cmd
      run: |
        set PATH=d:\qt-install\bin;%PATH%
        cd pro
        echo QMAKE_LFLAGS += '/LTCG' > local_quirks.pri
        qmake.exe -nocache "CONFIG+=release" single.pro
        jom.exe release -f Makefile

    - name: Set portable mode
      shell: bash
      run: |
        cd build
        mv release-64bit-msvc release
        cd release
        #echo "[common]" > vsedit.config
        #echo "vapoursynth_library_paths=.." >> vsedit.config

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: build/release

    - name: Compress artifact for release
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      run: |
        cd build\release
        7z a -t7z -mx=7 ../../vsedit-windows-x64.${{ github.event.inputs.tag }}.7z .

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: vsedit-windows-x64.${{ github.event.inputs.tag }}.7z
        fail_on_unmatched_files: true
        generate_release_notes: false
        prerelease: true
