name: Build Windows

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to upload to'
        default: ''

jobs:
  build-windows:
    runs-on: windows-2019

    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Download VapourSynth headers
      shell: bash
      run: |
        curl -s -o vs.zip -L https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth-*/ vapoursynth/
        mkdir -p "C:/Program Files/VapourSynth/sdk/include/"
        mv vapoursynth/include "C:/Program Files/VapourSynth/sdk/include/vapoursynth"

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: d:/qt-install
        key: ${{ runner.os }}-qt6-static

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.22.1'

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master

    - name: Download Qt
      shell: bash
      run: |
        curl -Lo qt.zip https://download.qt.io/archive/qt/6.2/6.2.2/single/qt-everywhere-src-6.2.2.zip
        unzip -q qt.zip
        mv qt-everywhere-src-6* qt-src

    - name: Build Qt
      shell: cmd
      run: |
        cmake --version
        ninja --version
        mkdir qt-build
        cd qt-build
        call ../qt-src/configure.bat --prefix=d:\qt-install -static -static-runtime -no-opengl -release -ltcg -qt-zlib -qt-sqlite -no-sql-odbc -qt-libpng -qt-libjpeg -skip qt3d -skip qtactiveqt -skip qtcharts -skip qtconnectivity -skip qtdatavis3d -skip qtdoc -skip qtmultimedia -skip qtwayland -skip qtscxml -skip qtwebview -skip qtwebengine -skip qttranslations -skip qtlottie -skip qtmqtt -skip qtopcua -skip qtserialport -skip qtserialbus -skip qtvirtualkeyboard -skip qtwebchannel -skip qtpositioning -skip qtquick3d -skip qtsensors -skip qtcoap -skip qtnetworkauth -skip qtquicktimeline -skip qtremoteobjects -skip qtshadertools -feature-windeployqt -no-feature-linguist -no-feature-designer -no-feature-pixeltool -no-feature-assistant -no-feature-distancefieldgenerator -no-feature-qtattributionsscanner -no-feature-qtplugininfo -no-feature-macdeployqt -no-feature-qdbus -no-feature-qtdiag
        ninja install

    - name: Build
      shell: cmd
      run: |
        set PATH=d:\qt-install\bin;%PATH%
        cd pro
        echo # > local_quirks.pri
        qmake.exe -nocache "CONFIG+=release" single.pro
        nmake.exe release -f Makefile

    - name: Set portable mode
      shell: bash
      run: |
        cd build
        mv release-64bit-msvc release
        cd release
        #echo "[common]" > vsedit.config
        #echo "vapoursynth_library_paths=.." >> vsedit.config

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: build/release

    - name: Compress artifact for release
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      run: |
        cd build\release
        7z a -t7z -mx=7 ../../vsedit-windows-x64.${{ github.event.inputs.tag }}.7z .

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: vsedit-windows-x64.${{ github.event.inputs.tag }}.7z
        fail_on_unmatched_files: true
        generate_release_notes: false
        prerelease: true
